### ISSUE TITLE
Ensure error-case behavior is reasonable

### ISSUE THREAD

**Issue by thefinn93** [AccelerateNetworks/fusionpbx-rest-api#2]
in particular this came up because it isnt clear that `destination-details` will give a reasonable not found response if the destination doesn't exist, but in general the error reporting is arbitrary and poorly documented.

**Comment by kylebown1** [comment]
@thefinn93 There's a few bugs that I'm working out myself, But this gave a really good headstart but essentially of the back of this I'm building a more in-depth API, So keep an eye out on my github i will post it in the coming weeks

**Comment by thefinn93** [comment]
Feel free to submit PRs
