### ISSUE TITLE
JSON response for destination-details contains nested JSON

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/fusionpbx-rest-api#5]
The "destination_actions" field in a valid response from a "action": "destination-details" query for a specific dialed number is quoted like a JSON string, but the value of the field is actually more JSON. Ideally this field would be a JSON array if you really can have multiple actions like the field name "destination-actions" implies. If it only ever returns a single object then I would expect this field just to be that JSON formatted object, not a string.

Current JSON response:
```
{"domain_uuid":"3da3f086-1dda-4a29-9c72-940baa430771","destination_uuid":"d5de5110-0f6d-4f33-a241-6a28914e70fb","dialplan_uuid":"3952ebb0-8186-4b26-9943-74207803cecd","fax_uuid":null,"destination_type":"inbound","destination_number":"","destination_number_regex":"^\\+?1?()$","destination_caller_id_name":null,"destination_caller_id_number":null,"destination_cid_name_prefix":null,"destination_context":"public","destination_record":null,"destination_accountcode":null,"destination_app":"transfer","destination_data":"5000
XML peakpotentialpt.sip.callpipe.com","destination_enabled":"true","destination_description":"Main
Number","destination_prefix":"1","destination_type_voice":null,"destination_type_fax":null,"destination_type_text":null,"destination_alternate_app":null,"destination_alternate_data":null,"destination_trunk_prefix":null,"destination_area_code":null,"destination_condition_field":null,"destination_hold_music":null,"user_uuid":null,"group_uuid":null,"destination_type_emergency":null,"destination_order":null,"destination_distinctive_ring":null,"destination_conditions":null,"destination_actions":"[{\"destination_app\":\"transfer\",\"destination_data\":\"5000
XML peakpotentialpt.sip.callpipe.com\"}]","insert_date":null,"insert_user":null,"update_date":"2023-04-06
05:35:41.570036+00","update_user":null}

```

**Comment by thefinn93** [comment]
This is fixed in 2ff6da7, which has been deployed to prod

**Comment by uncheckederror** [comment]
This change broke JSON parsing in my client apps when it went live. 

If you could have provided an example of the updated JSON format and set a timeline for pushing this build that would have been cool.

**Comment by thefinn93** [comment]
ooo sorry, didn't realize this needed to be coordinated. Should I revert the change on prod?

**Comment by uncheckederror** [comment]
Naw, I just pushed new builds to fix it, but it took me a little bit to figure out.
